### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by canedoly** [high-brow/Vusaline#4] opened 2022-02-04 17:06 UTC
after i started using vusaline, i've noticed that whenever i join some server that isn't my local one, casual & community my game just crashes
my loading screen when i join a game, is the same loading screen used for demo's
could you help me with that?

**Comment by movementplaya** [comment] 2022-02-04 23:09
Hello, may I ask, when this crashing occurs, are you using any mods for the game? And have these issues only started occurring with Vusaline?

**Comment by canedoly** [comment] 2022-02-05 08:44
I forgot to add that crashing wasn't always, but this crashing only happens whenever I load into a server (when the loading bar is done), and the causes for it were because of an cheat. Also do you know why I have the same loading screen which is used for demos.
EDIT: the crashing fully stopped, it was caused by a cheat, but I still don't know why I have the demo loading screen

**Comment by NekoAlosama** [comment] 2022-02-08 21:45
a cheat?
edit: nvm saw your profile

**Comment by movementplaya** [comment] 2022-02-08 23:29
After testing, I can confirm it is Vusaline creating the loading screen bug. However, it a low priority issue and I'm not entirely sure of it's nature and therefore if it is fixable. I will keep it in mind, though. As far as cheats are concerned, I have not tested nor can I guarantee compatibility with any cheats.

**Comment by canedoly** [comment] 2022-02-26 17:38
About that loading screen, I think its caused by a mod, idk which one tho
Also quick question it is important to keep vusaline updated constantly? Or I can have the version from Dec 8th and still be good.

**Comment by movementplaya** [comment] 2022-02-26 23:57
Hello, updating Vusaline is completely optional, however, I highly recommend updating in order to get the fullest benefit and to avoid possible bugs.

**Comment by felikcat** [comment] 2022-03-22 22:41
> After testing, I can confirm it is Vusaline creating the loading screen bug. However, it a low priority issue and I'm not entirely sure of it's nature and therefore if it is fixable. I will keep it in mind, though. As far as cheats are concerned, I have not tested nor can I guarantee compatibility with any cheats.

Not a bug, it's a trick to reduce loading times by skipping the load of some vgui panels on loading screens.

**Comment by movementplaya** [comment] 2022-03-23 01:48
I assumed it was the play demo trick, but never got round to testing it. Now I am sure it's not fixable and therefore won't be fixed.

**Closed as completed** 2022-03-23 01:48 UTC
Labels: wontfix
